log_dir = "/Users/aijaz/src/Aijaz/pytaskforest/example/logs"
job_dir = "/Users/aijaz/src/Aijaz/pytaskforest/example/jobs"
family_dir = "/Users/aijaz/src/Aijaz/pytaskforest/example/families"
instructions_dir = "/Users/aijaz/src/Aijaz/pytaskforest/example/instructions"

calendars.daily = [
  "*/*/*"
]
calendars.mondays = [
  "every Monday */*"
]
primary_tz = "America/Chicago"
