FROM python:slim

WORKDIR /
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY pytf/pytf_worker.py .
ENTRYPOINT ["celery", "-A", "pytf_worker", "worker", "--loglevel=INFO", "-Q", "default", "--concurrency=1"]
