FROM python:3.12

WORKDIR /
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
RUN mkdir pytf
COPY pytf pytf
ENTRYPOINT ["celery", "-A", "pytf.pytf_worker", "worker", "--loglevel=INFO", "-Q", "default", "--concurrency=1"]
