FROM python:alpine

WORKDIR /
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
RUN mkdir pytf
COPY pytf/* pytf
COPY pytf.py .
ENTRYPOINT ["python3", "-u", "/pytf.py", "main"]
