version: '3'

services:
   pytf_c:
      image: pytf_i
      volumes:
         - /Users/aijaz/src/Aijaz/pytaskforest/example:/pytf_root
      depends_on:
         - rabbitmq_c

   worker_c:
      image: worker_i
      volumes:
         - /Users/aijaz/src/Aijaz/pytaskforest/example:/pytf_root
      depends_on:
         - rabbitmq_c

   rabbitmq_c:
      image: rabbitmq_i
      ports:
      - 5672:5672
