version: '3'

services:
   aijaz_nginx_c:
      image: aijaz_nginx_i
      volumes:
         - ./document_root:/var/www/document_root
      ports:
         - "80:80"

   aijaz_flask_c:
      image: aijaz_flask_i
      expose:
         - "8000"

   aijaz_pg_c:
      image: aijaz_pg_i
      ports:
         - 5432:5432
      volumes:
         -  /tmp/pg_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_PASSWORD='mysecretpassword'
