version: '3'

services:
   pytf_c:
      image: pytf_i
      volumes:
         - ./example:/pytf_root
      command:
         -  /pytf.py main

   worker_c:
      image: worker_i
      volumes:
         - ./example:/pytf_root
      command:
         -  celery -A pytf.pytf_worker worker --loglevel=INFO -Q default --concurrency=1
